### PR TITLE
Fixes #684 update latest core

### LINKED ISSUE #684: Update to the latest core
@msevestre There has been a bug in core for creating default importer configuration for a file that @abdelr fixed some time ago, but I don't think it is in the core version of ospsuite-r. I wanted to update the core but then realized that we should also change the version of the package to 11, no? Either way, could you update it (and make a separate PR so I can see and learn how to do it in future).

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

**Comment by msevestre** [comment]
@PavelBal Trying to see if this works...

**Comment by IndrajeetPatil** [comment]
Out of curiosity: Do you change the versions manually or is there an automated way to do so?

**Comment by msevestre** [comment]
It's done automatically using the appveyor script. I patch the description file using the version provided by appveyor

**Comment by PavelBal** [comment]
`Message: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0,`

lol, it's always such a pain getting all versions right..

**Comment by msevestre** [comment]
Yeah it's a new dependency of autofac.... I'll add it soon.this should solve the issue

**Comment by msevestre** [comment]
trying...

**Comment by msevestre** [comment]
Ok the build we fail until we merge the changes from the CKD branch in PKSim into develop. 
@Yuri05 When can you review those? We have some open questions regarding parameters readonlhy etc.. but we can solve this later maybe?

**Pull request merged**
