### PR TITLE
Add documentation how to vary RHS params in SimulationBatch

### PR DESCRIPTION
**Pull request by PavelBal**

### CODE REVIEW

**Comment by PavelBal** [comment]
Proposal from @rwmcintosh - add a new argument `stateVariableParams` to the function, so `createSimulationBatch(simulation, parametersOrPaths = NULL, stateVariableParams = NULL, moleculesOrPaths = NULL)`.

@msevestre @Yuri05 what do you think?

**Comment by Yuri05** [comment]
> Proposal from @rwmcintosh - add a new argument `stateVariableParams` to the function, so `createSimulationBatch(simulation, parametersOrPaths = NULL, stateVariableParamsOrPaths = NULL, moleculesOrPaths = NULL)`.
> 
> @msevestre @Yuri05 what do you think?

why not

**Comment by PavelBal** [comment]
> Proposal from @rwmcintosh - add a new argument stateVariableParams to the function, so createSimulationBatch(simulation, parametersOrPaths = NULL, stateVariableParamsOrPaths = NULL, moleculesOrPaths = NULL).

I realized this is not that straightforward. `SimulationBatch$addRunValues()` supports adding values for parameters and initial values of molecules, and RHS params should be in the `molecules` list. If we want to extend the `createSimulationBatch` function by the argument for state variable parameters, `addRunValues` should support this too, but this is implemented in .NET. IMO too much overhead for now.

**Comment by PavelBal** [comment]
@Yuri05 @msevestre @Felixmil pls review

**Pull request merged**
