### PR TITLE
80 implement set parameters

### PR DESCRIPTION
**Pull request by PavelBal**

### CODE REVIEW

**Comment by msevestre** [comment]
@PavelBal THis is a bit tricky here because you started your work of my branch. Now all my commits are also included. Unless there is anything major to change, I'd suggest to merge my PR #115 and then you rebase your changes on develop. Does it make sense?

**Comment by PavelBal** [comment]
I don't understand this. Why does the build fail with
https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-r/builds/26636787#L362
```

> #' simPath <- system.file("extdata", "simple.pkml", package = "ospsuite")
363> sim <- loadSimulation(simPath)
364Error in rClr::clrCall(simulationLoader, "LoadSimulation", pkmlSimulationFile) : 
365  object 'simPath' not found
```

though I've just copied the path from the examlpe of the functions above?

**Comment by PavelBal** [comment]
> @PavelBal THis is a bit tricky here because you started your work of my branch. Now all my commits are also included. Unless there is anything major to change, I'd suggest to merge my PR #115 and then you rebase your changes on develop. Does it make sense?

Hmm, I thought only my changes will be shown after #115 has been merged...

**Comment by msevestre** [comment]
IT is not merged now so ALL The changes are showing up. Very hard to tell what **you** changes unless I go to each single commit

**Pull request closed without merging**
