### PR TITLE
With multiple data sets and groups, legend symbols are overriden

### LINKED ISSUE #1206: `plotIndividualTimeProfile` - wrong legend symbols
```
manyObsDC <- readRDS(getTestDataFilePath("manyObsDC"))
manyObsDC$removeGroupAssignment(names = "Vergin 1995.Iv")

dataSet3 <- DataSet$new(name = "Data set 3")
dataSet3$setValues(xValues = 1, yValues = 1, yErrorValues = 1)
dataSet4 <- DataSet$new(name = "Data set 4")
dataSet4$setValues(xValues = 1, yValues = 1, yErrorValues = 1)

manyObsDC$addDataSets(c(dataSet3, dataSet4))

plotIndividualTimeProfile(manyObsDC)
```

image

### PR DESCRIPTION
**Pull request by svavil**
Fixes #1206

### CODE REVIEW

**Review by Felixmil — COMMENTED** [review]
I think this should be implemented in {tlf} instead. Here we can see that the proposed changes have unwanted side effects on the legends:

| Before | After |
|--------|-------|
|image|image|
|image|image|

**Comment by PavelBal** [comment]
> I think this should be implemented in {tlf} instead. Here we can see that the proposed changes have unwanted side effects on the legends:

Could you try to fix it in TLF, then?

**Comment by Felixmil** [comment]
> Could you try to fix it in TLF, then?

@PavelBal is is actually related to the way the default dataMapping is constructed in OSPSR for this kind of plot. More info / discussions in [original issue](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1206#issuecomment-1486454900)

**Comment by PavelBal** [comment]
Why closed? Is this fixed? @svavil

**Comment by svavil** [comment]
@PavelBal my understanding was that we are not going to push these particular changes due to side effects (shaded regions on markers), and we need another approach here? The issue #1206 that was the reason for the PR is still there, and if we come up with a working solution, we could then close the issue, but not with this PR. I might be missing something?

**Comment by PavelBal** [comment]
Oh sorry, I thought it es an issue and not a PR. All good then.

**Pull request closed without merging**
