### PR TITLE
udpate core

### PR DESCRIPTION
**Pull request by rwmcintosh**

### CODE REVIEW

**Comment by msevestre** [comment]
Build fails

**Comment by PavelBal** [comment]
It's been failing for months now. No idea why, but building vignettes on AppVeyor behaves differently than locally (or on GitHub Actions) and fails.

**Comment by rwmcintosh** [comment]
Is it these two lines being skipped?

```
stateVariableParam <- getParameter(path = "Organism|Lumen|Stomach|Liquid", container = sim1)
print(stateVariableParam)
```

See the log lines 121-123. I don't see all the lines from the source code
[efficient-calculations.Rmd.log](https://github.com/user-attachments/files/15865812/efficient-calculations.Rmd.log)

**Comment by rwmcintosh** [comment]
Wait, this check is being done against the rSharp branch, not develop

**Comment by rwmcintosh** [comment]
ok, it's not a different branch, but a different AppVeyor build somehow.

**Comment by PavelBal** [comment]
> In summary - I have no idea what's going on.

No one has.

**Review by PavelBal — APPROVED** [review]

**Comment by msevestre** [comment]
it's time we get rid off Appveyor for building R stuff

**Pull request merged**
