### PR TITLE
Fix parsing issue in pkResultsToDataFrame when reading csv with NA values

### PR DESCRIPTION
**Pull request by rengelke**
Fix parsing issue in pkResultsToDataFrame when reading csv with NA values

Warning message when convering `pkAnalyses` to `pkAnalysesData` using `pkAnalysisToDataFrame()`. Occurs when reading csv-file with `readr::read_csv` which contains "NaN" or "Infinity". 

````
One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat <- vroom(...)
  problems(dat)
````

Closes  esqLABS/esqlabsR#667

### CODE REVIEW

**Comment by PavelBal** [comment]
> Error in loadNamespace(x) : there is no package called 'spelling'

@Yuri05 @Felixmil Where does this suddenly come from? AppVeyor keeps coming up with new errors to keep it interesting?

**Comment by Felixmil** [comment]
> @Yuri05 @Felixmil Where does this suddenly come from? AppVeyor keeps coming up with new errors to keep it interesting?

It appears to be a temporary connection issue (URLs could not be reached). I suggest to restart the action.

**Comment by PavelBal** [comment]
Still failing with the same error.

**Comment by PavelBal** [comment]
Why can't is just read the values as `NaN` or `Inf`?

**Comment by Felixmil** [comment]
I think the issue was temporary, getting packages installed just worked in this workflow run: https://ci.appveyor.com/project/open-systems-pharmacology-ci/ospsuite-r-rsharp/builds/49973288

**Comment by rengelke** [comment]
> Why can't it just read the values as `NaN` or `Inf`?

The main problem is that `pkParameterResultsFile` contains literal `"Infinity"` values, which need explicit definition as `na = "Infinity"` when reading the CSV file. Alternatively, changing 'Infinity' to `Inf` would allow `readr::read_csv` to parse them as numeric values without issues."

**Review by PavelBal — APPROVED** [review]

**Pull request merged**
