### PR TITLE
closes #740

### LINKED ISSUE #740: `Printable` from utils?
Utils have a Printable class, ospsuite has a printable class...

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Remove internal copy of `Printable` and update docs for the same.

### CODE REVIEW

**Review by PavelBal — APPROVED** [review]

**Comment by IndrajeetPatil** [comment]
Failing build is not related to this PR: it's already failing in `develop` branch.

**Comment by msevestre** [comment]
Let me fix this one sec

**Comment by msevestre** [comment]
ok there is a merge conflict here. I only change the DataSet$new() line

**Comment by IndrajeetPatil** [comment]
Huh, how can that be?! I didn't touch the `data-combined.R` file.

**Comment by IndrajeetPatil** [comment]
Never mind, fixed it.

**Pull request merged**
