### PR TITLE
Implement `plotObservedVsSimulated()`

### LINKED ISSUE #804: Add function to interpolate predicted data
As mentioned in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/674#issuecomment-987833373, `DataCombined` object needs to provide data for creating predicted versus observed plot. 

image

For such a plot, the data needs to be _paired_. That is, at a given time (`xValues`), there needs to be a _single_ pair of `yValues` for observed and simulated data.

The `$toObsVsPredDataFrame()` public method for `DataCombined` will provide such a dataframe.

### LINKED ISSUE #924: Create `plotObservedVsSimulated()` function
Plot discussed in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/discussions/809
Interpolation function discussed in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/804

Related to #674

### LINKED ISSUE #1012: plotObservedVsSimulated(): error when DataCombined only contains observed or simulated results
```
myCombDat <- DataCombined$new()

# load the simulation
sim <- loadTestSimulation("MinimalModel")
simResults <- importResultsFromCSV(
  simulation = sim,
  filePaths = getTestDataFilePath("Stevens_2012_placebo_indiv_results.csv")
)

myCombDat$addSimulationResults(
  simResults,
  quantitiesOrPaths = c(
    "Organism|Lumen|Stomach|Dapagliflozin|Gastric retention",
    "Organism|Lumen|Stomach|Dapagliflozin|Gastric emptying",
    "Organism|Lumen|Stomach|Metformin|Gastric retention"
  )
)

Following datasets were specified to be grouped but not found:
Organism|Lumen|Stomach|Dapagliflozin|Gastric emptying
Organism|Lumen|Stomach|Dapagliflozin|Gastric retention
Organism|Lumen|Stomach|Metformin|Gastric retention

Error in `dplyr::arrange()` at OSPSuite-R/R/utilities-units.R:585:2:
! Problem with the implicit `transmute()` step.
✖ Problem while computing `..1 = .rowidInternal`.
Caused by error:
! object '.rowidInternal' not found
Run `rlang::last_error()` to see where the error occurred.
Warning messages:
1: Unknown or uninitialised column: `yUnitSplit`. 
2: Unknown or uninitialised column: `molWeightSplit`. 
```

Instead, it should produce an empty plot (and, if defined in the plot configuration, title subtitle and so on).

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
TODO

- [x] Implement interpolation function
- [x] Implement `plotObservedVsSimulated()`
- [x] tests for `plotObservedVsSimulated()` 
- [x] check comments
- [x] handle empty `DataCombined` objects
- [x] Address Pavel's code review comments (https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/945#issuecomment-1173770611)

Features that need to be implemented in _tlf_, and thus should not block this PR from being merged:
- https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/332
- https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/333

Related to #674 

Discussed in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/discussions/809

Closes #804 
Closes #924
Closes [#1010](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1010)
Closes [#1011](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1011)
Closes #1012

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Current output:

(The pattern for `distal` group looks odd, but I am not sure if it's due to interpolation not working as expected or because the dataset itself is messy.)

- If you are wondering about the dots lingering close to the _x_-axis, those will be removed automatically once https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/308 is fixed.
- Should the legend position be different for this plot, since there is expected to be a positive correlation between these points most of the time and so the legend will always occlude the data?

```r
library(ospsuite)

# load the simulation
sim <- loadTestSimulation("MinimalModel")
simResults <- importResultsFromCSV(
  simulation = sim,
  filePaths = getTestDataFilePath("Stevens_2012_placebo_indiv_results.csv")
)

# import observed data (will return a list of DataSet objects)
dataSet <- loadDataSetsFromExcel(
  xlsFilePath = getTestDataFilePath("CompiledDataSetStevens2012.xlsx"),
  importerConfiguration = loadDataImporterConfiguration(getTestDataFilePath("ImporterConfiguration.xml"))
)

# create a new instance and add datasets
myCombDat <- DataCombined$new()
myCombDat$addSimulationResults(
  simResults,
  quantitiesOrPaths = c(
    "Organism|Lumen|Stomach|Dapagliflozin|Gastric retention",
    "Organism|Lumen|Stomach|Dapagliflozin|Gastric emptying",
    "Organism|Lumen|Stomach|Metformin|Gastric retention"
  )
)

myCombDat$addDataSets(dataSet)

myCombDat$setGroups(
  names = c(
    "Organism|Lumen|Stomach|Dapagliflozin|Gastric emptying",
    "Stevens_2012_placebo.Sita_dist",
    "Organism|Lumen|Stomach|Dapagliflozin|Gastric retention",
    "Stevens_2012_placebo.Sita_proximal",
    "Organism|Lumen|Stomach|Metformin|Gastric retention",
    "Stevens_2012_placebo.Sita_total"
  ),
  groups = c("distal", "distal", "proximal", "proximal", "total", "total")
)

# default
plotObservedVsSimulated(myCombDat)
```

eg

**Comment by IndrajeetPatil** [comment]
Some tests are going to fail because the snapshots need to be updated for changes made to _tlf_. 

I can only do this when I am back from vacation.

**Comment by PavelBal** [comment]
- Default legend position sould be right bottom inside
- The identity line should *always* go from bottom left to top right
- The argument `foldDistance` should only include fold values different from 1. 1 always must be present. The dafault value should be 2 (only).
- If possivle, every fold line should have a disctinct style
- Add error bars to the observed data (would be in horizontal space).

**Comment by PavelBal** [comment]
Use this for more meaningful mapping:

```
myCombDat <- DataCombined$new()
myCombDat$addDataSets(dataSet)
myCombDat$addSimulationResults(
  simResults,
  quantitiesOrPaths = c(
    "Organism|Lumen|Stomach|Metformin|Gastric retention",
    "Organism|Lumen|Stomach|Metformin|Gastric retention distal",
    "Organism|Lumen|Stomach|Metformin|Gastric retention proximal"
  )
)

myCombDat$setGroups(
  names = c(
    "Organism|Lumen|Stomach|Metformin|Gastric retention",
    "Organism|Lumen|Stomach|Metformin|Gastric retention distal",
    "Organism|Lumen|Stomach|Metformin|Gastric retention proximal",
    "Stevens_2012_placebo.Placebo_total",
    "Stevens_2012_placebo.Placebo_distal",
    "Stevens_2012_placebo.Placebo_proximal"
  ),
  groups = c("Solid total", "Solid distal", "Solid proximal", "Solid total", "Solid distal", "Solid proximal")
)
```

**Comment by PavelBal** [comment]
Fold lines are somehow not shown when scaling is not log:

```
plotConfig <- DefaultPlotConfiguration$new()
plotConfig$xAxisScale <- "lin"
plotConfig$yAxisScale <- "lin"
plotObservedVsSimulated(myCombDat, defaultPlotConfiguration = plotConfig)
```

image

**Comment by PavelBal** [comment]
Why is there no antialiasing by default? Base r plot does it when exporting to clipboard, I think.

**Comment by IndrajeetPatil** [comment]
> Why is there no antialiasing by default? Base r plot does it when exporting to clipboard, I think.

I have no idea about this; never experienced it myself. And even if it were to be an issue, this would have to be about RStudio's plot pane.

**Comment by IndrajeetPatil** [comment]
Thanks for the feedback!

The example you provided is much better for testing and the output also looks much better:

```r
library(ospsuite)

# load the simulation
sim <- loadTestSimulation("MinimalModel")
simResults <- importResultsFromCSV(
  simulation = sim,
  filePaths = getTestDataFilePath("Stevens_2012_placebo_indiv_results.csv")
)

# import observed data (will return a list of DataSet objects)
dataSet <- loadDataSetsFromExcel(
  xlsFilePath = getTestDataFilePath("CompiledDataSetStevens2012.xlsx"),
  importerConfiguration = loadDataImporterConfiguration(getTestDataFilePath("ImporterConfiguration.xml"))
)

# create a new instance and add datasets
myCombDat <- DataCombined$new()
myCombDat$addDataSets(dataSet)
myCombDat$addSimulationResults(
  simResults,
  quantitiesOrPaths = c(
    "Organism|Lumen|Stomach|Metformin|Gastric retention",
    "Organism|Lumen|Stomach|Metformin|Gastric retention distal",
    "Organism|Lumen|Stomach|Metformin|Gastric retention proximal"
  )
)

myCombDat$setGroups(
  names = c(
    "Organism|Lumen|Stomach|Metformin|Gastric retention",
    "Organism|Lumen|Stomach|Metformin|Gastric retention distal",
    "Organism|Lumen|Stomach|Metformin|Gastric retention proximal",
    "Stevens_2012_placebo.Placebo_total",
    "Stevens_2012_placebo.Placebo_distal",
    "Stevens_2012_placebo.Placebo_proximal"
  ),
  groups = c("Solid total", "Solid distal", "Solid proximal", "Solid total", "Solid distal", "Solid proximal")
)

plotObservedVsSimulated(myCombDat)
```

obs_vs_pred

**Comment by IndrajeetPatil** [comment]
> What does the argument `smoother` do?

It adds a regression line (either linear or loess) to the plot in addition to the other lines. 

I am not sure if this is needed; I added it only because `tlf::plotObsVsPred()` supports it.

**Comment by PavelBal** [comment]
> It adds a regression line (either linear or loess) to the plot in addition to the other lines.

I would remove it, not a use case I have in mind... good to know it is supported, if anyone will request the feature we can easily add it later.

**Comment by IndrajeetPatil** [comment]
@msevestre, @Yuri05 This PR is ready for a review. Thanks.

**Comment by IndrajeetPatil** [comment]
> ```
> Warning message:
> In plotObservedVsSimulated(myCombDat, defaultPlotConfiguration = plotConfig,  :
>   Linear scale is inappropriate when `foldDistance` argument is specified.
> ```
> 
> Why that?

@pchelle will post some example plots with linear and log scales in Discussion #809 to discuss this further.

**Comment by IndrajeetPatil** [comment]
Observed data is plotted with error bars now. 

Note that the error bar is missing in the plot below for some data points because the error value is 0.

obs_vs_pred

**Comment by Yuri05** [comment]
Should we display the error bars in the same way as usually?
grafik

**Comment by IndrajeetPatil** [comment]
> Should we display the error bars in the same way as usually?

This would be easy to do by setting `height` to some non-zero value in `geom_errorbarh()`.

I personally find those vertical edges distracting. Plus, they don't convey any additional information, so it's just adding clutter to an already busy plot. So I'd prefer not adding the edges.

I'm curious to hear what others think.

**Comment by Yuri05** [comment]
>they don't convey any additional information, so it's just adding clutter to an already busy plot. So I'd prefer not adding the edges.

In general, I agree. 
However we display error bars always like this ([example](https://github.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library/blob/master/Alfentanil/alfentanil_evaluation_report.md#33-concentration-time-profiles)) and looking at the [plots by others](https://www.google.com/search?q=time+profile+error+bars&tbm=isch&ved=2ahUKEwikzPjyxPr4AhUjafEDHV8aB9IQ2-cCegQIABAA&oq=time+profile+error+bars&sclient=img&ei=ni3RYqSFOKPSxc8P37SckA0&bih=749&biw=1536&client=firefox-b-d) - same in the most cases (not always though)

**Comment by IndrajeetPatil** [comment]
@Yuri05 Does this mean that we should also be displaying error bars with edges in profile plots?

Currently, we have error bars without the edge segments:

image

**Comment by PavelBal** [comment]
> Does this mean that we should also be displaying error bars with caps in profile plots?

Hmm yes, I did not realize this but yes, it is usual to display caps for error bars.

**Comment by Yuri05** [comment]
>Does this mean that we should also be displaying error bars with caps in profile plots?

I would say yes :)

**Comment by IndrajeetPatil** [comment]
Okay, I've created an issue it _tlf_ to add caps to error bars: https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/333

Once it is added there, it will automatically be included in the _ospsuite_ plots as well.

**Comment by IndrajeetPatil** [comment]
@PavelBal and @Yuri05 I've created issues for features that need to be implemented in _tlf_, and thus should not block this PR from being merged:

- https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/332
- https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/333

I don't want to keep this pending anymore, since this is blocking me from working on #1002.

**Review by Yuri05 — APPROVED** [review]

**Comment by IndrajeetPatil** [comment]
Thanks, Yuri.

@PavelBal Let me know if you have any other comments over and above the ones that have already been addressed.

**Pull request merged**
