### PR TITLE
Update core to 11.1.59

### PR DESCRIPTION
**Pull request by PavelBal**

### CODE REVIEW

**Comment by Yuri05** [comment]
11.1.60 is already available ;)

**Comment by PavelBal** [comment]
Yes, but not in PK-Sim... I wanted to update so the build is passing (currently develop branch is failing).

**Review by Yuri05 — APPROVED** [review]

**Comment by PavelBal** [comment]
@Yuri05 Can you trigger a re-build of the nightly, please?

**Comment by Yuri05** [comment]
rebuild failed...

**Comment by PavelBal** [comment]
Yes, PK-Sim has been updated but after the nightly has been built... This is annoying.

**Comment by PavelBal** [comment]
Could you try again?

**Comment by Yuri05** [comment]
Todays nightly succeeded as far as I can see

**Pull request merged**
