### PR TITLE
Add three data sets for aciclovir simulations

### PR DESCRIPTION
**Pull request by PavelBal**
@IndrajeetPatil Added three data sets that you could use as another example for https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/822
Especially for unit conversion - the data sets have the dimension `Concentration` as opposed to `Fraction` in the other example, converting the units migth be more "interesting" (requires molecular weight sometimes).

Something like: 

```
#Load and run simulation
sim <- loadSimulation(system.file("extdata", "Aciclovir.pkml", package = "ospsuite"))
simulationResults <- runSimulations(sim)

#Load observed data
obsData <- lapply(c("ObsDataAciclovir_1.pkml",
                    "ObsDataAciclovir_2.pkml",
                    "ObsDataAciclovir_3.pkml"),
                  \(x){loadDataSetFromPKML(getTestDataFilePath(x))})

#Create and populate DataCombined
outputPath <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
aciclovirData <- DataCombined$new()
aciclovirData$addSimulationResults(simulationResults = simulationResults,
                                   quantitiesOrPaths = outputPath)
aciclovirData$addDataSets(obsData)
aciclovirDf <- aciclovirData$toDataFrame()

```

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Very helpful, thanks!

**Comment by msevestre** [comment]
should we merge this or what?

**Comment by PavelBal** [comment]
No, there are just some data sets (as pkml) for better examples for @IndrajeetPatil. Maybe he can download and use them locally, and then we can delete this branch.

**Comment by msevestre** [comment]
ok. Let's do this then.

**Comment by PavelBal** [comment]
@msevestre @IndrajeetPatil Adding three data set we talked about yesterday.

**Review by IndrajeetPatil — APPROVED** [review]

**Pull request merged**
