### PR TITLE
Passing font size options from plotConfiguration objects to tlf objects

### LINKED ISSUE #1184: Cannot change x axis tick size in a default plot configuration
```
oneObsDC <- readRDS(getTestDataFilePath("oneObsDC"))

plotConfig <- DefaultPlotConfiguration$new()
print(plotConfig$xAxisLabelTicksSize)
plotIndividualTimeProfile(oneObsDC, plotConfig)

plotConfig$xAxisLabelTicksSize <- 8
plotIndividualTimeProfile(oneObsDC, plotConfig)

plotConfig$xAxisLabelTicksSize <- 16
plotIndividualTimeProfile(oneObsDC, plotConfig)
```

`plotConfig$xAxisLabelTicksSize`
 is ignored - all plots look the same
 
 
image

Tried to change xAxisSize with `plotConfig$xAxisSize <- 16` and still the same.

@pchelle or am I trying the set the wrong parameter? I want to change the size of axis tick labels (the numbers "0, 5, 10" etc)

### PR DESCRIPTION
**Pull request by svavil**
Fixes #1184 . Updates several snapshots that were seemingly produced with default axis font instead of custom.

### CODE REVIEW

**Review by pchelle — APPROVED** [review]

**Review by PavelBal — CHANGES_REQUESTED** [review]
Build is failing

**Comment by PavelBal** [comment]
Outdated TLF I assume....

**Comment by PavelBal** [comment]
No... I just cannot reproduce.

**Review by PavelBal — APPROVED** [review]

**Comment by PavelBal** [comment]
@Yuri05 Too late for the release?

**Comment by Yuri05** [comment]
>Too late for the release?

Yes

**Comment by Yuri05** [comment]
I would say 11.2
If the next release of the ospsuite-R comes out **before** the release 12 of the suite - 11.2 is fine.
If it comes together with the suite 12 - we still can increase it before the release.

**Comment by PavelBal** [comment]
@Yuri05 I have incresed the version, please review if this is sufficient.

**Review by Yuri05 — APPROVED** [review]

**Pull request merged**
