### PR TITLE
change round brackets to square brackets in dimension names

### PR DESCRIPTION
**Pull request by abdullahhamadeh**
Enables intellisense in ospUnits lists such as Concentration (Mass)

### CODE REVIEW

**Comment by PavelBal** [comment]
Looks good for me.

**Comment by msevestre** [comment]
Build is failing but this is because pksim interface has changed. Will update

**Comment by PavelBal** [comment]
This has been closed without merging. @msevestre will it be updated?

**Comment by msevestre** [comment]
This was a mistake. I wanted to merge jt

**Pull request merged**
