### PR TITLE
Updated markers in plots corresponding to datasets

### LINKED ISSUE #1110: `plotObservedVsSimulated`, `plotResidualsVsSimulated`, `plotResidualsVsTime`: different symbols for data sets within one grou
In `plotIndividualTimeProfile`, if there are multiple observed data assigned to the same group, the data sets get different symbols:

```
simData <- simData <- withr::with_tempdir({
  df <- dplyr::tibble(
    IndividualId = c(0, 0, 0),
    `Time [min]` = c(0, 2, 4),
    `Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood) [µmol/l]` = c(0, 4, 8)
  )
  readr::write_csv(df, "SimResults.csv")
  importResultsFromCSV(sim, "SimResults.csv")
})

obsData <- DataSet$new(name = "Observed")
obsData$setValues(xValues = c(1, 3, 3.5, 4, 5), yValues = c(1.9, 6.1, 7, 8.2, 1))
obsData$xUnit <- "min"
obsData$yDimension <- ospDimensions$`Concentration (molar)`

myDC <- DataCombined$new()
myDC$addSimulationResults(simData, groups = "myGroup")
myDC$addDataSets(obsData, groups = "myGroup")

# Add second obs data
obsData2 <- DataSet$new(name = "Observed 2")
obsData2$setValues(xValues = c(0, 3, 4, 4.5, 5.5), yValues = c(2.9, 5.1, 3, 8.2, 1))
obsData2$xUnit <- "min"
obsData2$yDimension <- ospDimensions$`Concentration (molar)`

myDC$addDataSets(obsData2, groups = "myGroup")

plotIndividualTimeProfile(myDC)
```

image

This is the expected behavior. However, when using one of the `plot...vs...` functions, all points have the same symbol:

image

THe functions should also use differnt symbols for the different data sets.

### PR DESCRIPTION
**Pull request by svavil**
Closes #1110 . Adds a `shape` mapping into `{tlf}` plots, based on `name` in the `DataCombined` input objects.

### CODE REVIEW

**Comment by PavelBal** [comment]
@svavil according to the new snapshots, the legend now has only one symbol and does not respect the actually used symbols for the data sets.

**Review by PavelBal — CHANGES_REQUESTED** [review]
@svavil according to the new snapshots, the legend now has only one symbol and does not respect the actually used symbols for the data sets.

**Comment by svavil** [comment]
@PavelBal I've finally fixed the legend shapes. If multiple datasets are present, the legend will show the shape corresponding to one of them.

**Comment by svavil** [comment]
image
Issue #1110 is fixed by this PR.

**Comment by PavelBal** [comment]
@svavil looks good to me. One thing - let's always add tests for every bug we discover. Especially for plots, as the behavior may change without noticing it.

I have added the corresponding tests. Going to merge.

**Pull request merged**
