### PR TITLE
Fixes #467 Disable "Windows-only" tests if running under Linux

### LINKED ISSUE #467: Disable "Windows-only" tests if running under Linux
If testthat-tests are running under Linux: the tests which currently run only under Windows should be disabled.
Currently those tests are:
* all tests in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/tests/testthat/test-create-individual.R 
* all tests in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/tests/testthat/test-create-population.R
* the test "It can load a simulation whose name contains unicode characters" in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/develop/tests/testthat/test-unicode-support.R (regarding this one: in fact loading simulations with unicode chars in file names does work under Linux. However such files created under Windows and transferred to Linux make problems, because file names are changed then sometimes - nothing what ospsuite-R can fix here. It happens e.g. even if you zip a file on windows and unzip under Linux)

### PR DESCRIPTION
**Pull request by Yuri05**

### CODE REVIEW

**Comment by msevestre** [comment]
@Yuri05 I just triggered a new build for this one

**Comment by msevestre** [comment]
Going to merge this

**Comment by msevestre** [comment]
@Yuri05 Build is still failing. I have no idea why

**Comment by msevestre** [comment]
WTF
image

I think this package was just updated and the one required is not available anymore!

**Comment by msevestre** [comment]
image
vs
image

**Comment by Yuri05** [comment]
Well, no idea. We can wait couple of days and retry then
grafik

**Pull request merged**
