### PR TITLE
remove unused pander; ignore more files

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Seems to be unrelated to changes in this PR:

```r
Quitting from lines 30-43 (create-individual.Rmd) 
Error: processing vignette 'create-individual.Rmd' failed with diagnostics:
Could not find an installation of PK-Sim on the machine. Please install the OSPSuite or use 'initPKSim()' to specify the installation path
--- failed re-building 'create-individual.Rmd'
```

**Comment by PavelBal** [comment]
@msevestre PKSim not installed?

**Comment by msevestre** [comment]
Version mismatch here/. The lastest PKSim build is v10 whereas we are on v11 here. WE can merge safely and we need to create a v11 of PKSim. This will take a few days

**Comment by msevestre** [comment]
>WE can merge safely

and then we can scream loud and clear that @IndrajeetPatil broke the build

**Comment by IndrajeetPatil** [comment]
not-happening-nope

**Pull request merged**
