### PR TITLE
Improvements to profile plots when multiple datasets of a given type present per group

### LINKED ISSUE #980: `plotIndividualTimeProfile` - multiple observed data within one group should get different symbols
RIF 20mg qd 14d_DC

Panel B - there are two observed data sets, both having the same symbols. They should have different symbols.

In the legend, only one entry should be shown, using the symbol of the first observed data (so basically the legend should not change).

### LINKED ISSUE #982: `plotIndividualTimeProfile` multiple simulation results within one group are connected
plotIndividualTimeProfile 

Panels d and e - there are multiple simulated curves in one group - the last point of one curve is connected with the first point of the next curve.

### LINKED ISSUE #1051: `plotSimulatedVsObserved` y and x axis limits should be identical

### LINKED ISSUE #1052: `plotObservedVsSimulated` wrong results
For this individual time profile:

```
simFilePath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
sim <- loadSimulation(simFilePath)

simResults <- runSimulation(sim)

obsData <- lapply(c("ObsDataAciclovir_1.pkml", "ObsDataAciclovir_2.pkml", "ObsDataAciclovir_3.pkml"),
                    \(x){loadDataSetFromPKML(system.file("extdata", x, package = "ospsuite"))})

names(obsData) <- lapply(obsData, \(x){x$name})

outputPath <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
myDataCombined <- DataCombined$new()
# Add simulated results
myDataCombined$addSimulationResults(simulationResults = simResults,
                                    quantitiesOrPaths = outputPath,
                                    groups = "Aciclovir PVB")

# Add observed data set
myDataCombined$addDataSets(obsData$`Vergin 1995.Iv`, groups = "Aciclovir PVB")

plotIndividualTimeProfile(myDataCombined, plotConfig)
```

image

the corresponding  simulated-vs-observed plot looks like this:

image

- One point in for the "underpredicted" area, i.e., where simulated results are lower than the observed values (below the identity line) is missing.
- The points in the upper right corner do not make sense. There are no simulated values above 1000 µmol/l.

The plot should look like this (PK-Sim):

image

### LINKED ISSUE #1056: Don't run simulation each time for tests; use a stored example instead
Current code I am using in tests, which makes the test stochastic:

```r
populationCharacteristics <- createPopulationCharacteristics(
  species = Species$Human,
  population = HumanPopulation$Asian_Tanaka_1996,
  numberOfIndividuals = 50,
  proportionOfFemales = 50,
  weightMin = 30,
  weightMax = 98,
  weightUnit = "kg",
  heightMin = NULL,
  heightMax = NULL,
  ageMin = 0,
  ageMax = 80,
  ageUnit = "year(s)"
)

# Create population from population characteristics
result <- createPopulation(populationCharacteristics = populationCharacteristics)
myPopulation <- result$population

# Load simulation
simFilePath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
sim <- loadSimulation(simFilePath)

set.seed(123)
populationResults <- runSimulation(
  simulation = sim,
  population = myPopulation
)

myDataComb <- DataCombined$new()
myDataComb$addSimulationResults(populationResults)
```

Better to use a stored example. @PavelBal Can you please suggest an example to use for this test?

Currently, `plotPopulationTimeProfile()` is severely under-tested because I haven't been able to create many test cases.

### LINKED ISSUE #1058: Add more tests for `plotPopulationTimeProfile()`
Currently, there is only one example with a single simulated dataset in the `DataCombined` object. This is not enough.

```r
simFilePath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
sim <- loadSimulation(simFilePath)

populationResults <- importResultsFromCSV(
  simulation = sim,
  filePaths = system.file("extdata", "SimResults_pop.csv", package = "ospsuite")
)

myDataComb <- DataCombined$new()
myDataComb$addSimulationResults(populationResults)
plotPopulationTimeProfile(myDataComb)
```

There also need to be tests for:

- `DataCombined` object with multiple simulated and observed datasets with grouping but only one data type per group
- `DataCombined` object with multiple simulated datasets in a **single** group
- `DataCombined` object with multiple observed datasets in a **single** group

But I don't know what examples make sense here.

### LINKED ISSUE #1059: plotPopulationTimeProfile: Error bars not shown
```
simFilePath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
sim <- loadSimulation(simFilePath)

outputPaths <- c("Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)",
                 "Organism|Muscle|Intracellular|Aciclovir|Concentration")

#simResults <- runSimulation(sim, population = pop)
simResults <- importResultsFromCSV(simulation = sim, filePaths = system.file("extdata", "SimResults_pop.csv", package = "ospsuite"))

obsData <- lapply(c("ObsDataAciclovir_1.pkml", "ObsDataAciclovir_2.pkml", "ObsDataAciclovir_3.pkml"),
                  \(x){loadDataSetFromPKML(system.file("extdata", x, package = "ospsuite"))})

names(obsData) <- lapply(obsData, \(x){x$name})

myDataCombined <- DataCombined$new()
# Add simulated results
myDataCombined$addSimulationResults(simulationResults = simResults,
                                    quantitiesOrPaths = outputPaths[[1]],
                                    groups = "Aciclovir PVB")

# Add observed data set
myDataCombined$addDataSets(obsData$`Vergin 1995.Iv`, groups = "Aciclovir PVB")

plotIndividualTimeProfile(myDataCombined)
plotPopulationTimeProfile(myDataCombined)
```

Individual:
image

Population:

image

### LINKED ISSUE #1060: Nighty failing because of some snapshots outdated
@IndrajeetPatil @PavelBal 
Can we fix this please?

image

  Execution halted
Running the tests in 'tests/vdiffr.[rR]' failed.
Last 13 lines of output:
  < <polyline points='38.79,109.89 567.20,109.89 ' style='stroke-width: 0.53; stro
  : ke: #FFFFFF; stroke-linecap: butt;' />                                        
  < <polyline points='112.41,532.29 112.41,36.15 ' style='stroke-width: 0.53; stro
  : ke: #FFFFFF; stroke-linecap: butt;' />                                        
  < <polyline points='211.62,532.29 211.62,36.15 ' style='stroke-width: 0.53; stro
  : ke: #FFFFFF; stroke-linecap: butt;' />                                        
  < <polyline points='310.82,532.29 310.82,36.15 ' style='stroke-width: 0.53; stro
  : ke: #FFFFFF; stroke-linecap: butt;' />                                        
  < <polyline points='410.02,532.29 410.02,36.15 ' style='stroke-width: 0.53; stro
  : ke: #FFFFFF; stroke-linecap: butt;' />                                        
  < <polyline points='509.23,532.29 509.23,36.15 ' style='stroke-width: 0.53; stro
  : ke: #FFFFFF; stroke-linecap: butt;' />                                        
    </g>

### LINKED ISSUE #1062: `plotPopulationTimeProfile` - upper quantile is not shown
In the current version, only the mid quantile is shown as a line and the lower quantile as shaded area, the upper quantile is not presented:

```
simFilePath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
sim <- loadSimulation(simFilePath)

outputPaths <- c("Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)",
                 "Organism|Muscle|Intracellular|Aciclovir|Concentration")

#simResults <- runSimulation(sim, population = pop)
simResults <- importResultsFromCSV(simulation = sim, filePaths = system.file("extdata", "SimResults_pop.csv", package = "ospsuite"))

myDataCombined <- DataCombined$new()
# Add simulated results
myDataCombined$addSimulationResults(simulationResults = simResults,
                                    quantitiesOrPaths = outputPaths[[1]],
                                    groups = "Aciclovir PVB")

plotPopulationTimeProfile(myDataCombined, plotConfig, quantiles = c(.2, .5, .8))
```

image

### LINKED ISSUE #1064: `plotPopulationTimeProfile` range color does not match line color if multiple results are assigned to the same group
Both shaded areas should have the color of the line (blue). They will not be distinguishable, but that's fine.

```
simFilePath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
sim <- loadSimulation(simFilePath)

outputPath <- c("Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)",
                "Organism|Muscle|Intracellular|Aciclovir|Concentration")

simResults <- importResultsFromCSV(simulation = sim, filePaths = system.file("extdata", "SimResults_pop.csv", package = "ospsuite"))

obsData <- lapply(c("ObsDataAciclovir_1.pkml", "ObsDataAciclovir_3.pkml"),
                  \(x){loadDataSetFromPKML(system.file("extdata", x, package = "ospsuite"))})

names(obsData) <- lapply(obsData, \(x){x$name})


myDataCombined <- DataCombined$new()
# Add simulated results
myDataCombined$addSimulationResults(simulationResults = simResults,
                                    quantitiesOrPaths = outputPaths,
                                    groups = "Aciclovir PVB")

plotPopulationTimeProfile(myDataCombined)
```

image

### LINKED ISSUE #1065: Add examples in the manual for `DataCombined` and related plotting functions

### LINKED ISSUE #1066: unnecessary files in .tar.gz packages
grafik

zip package is ok
grafik

### LINKED ISSUE #1076: Fix failing tests
```
== Failed tests ================================================================
-- Failure (test-plot-individual-time-profile.R:51:3): It creates default plots as expected for both observed and simulated --
Snapshot of `testcase` to 'plot-individual-time-profile/default-plot-both.svg' has changed
* Download and unzip run artifact
* Copy 'tests/testthat/_snaps/plot-individual-time-profile/default-plot-both.new.svg' to local test directory
* Run `testthat::snapshot_review('plot-individual-time-profile/')` to review changes
Backtrace:
    x
 1. \-vdiffr::expect_doppelganger(title = "default plot - both", fig = plotIndividualTimeProfile(myCombDat)) at test-plot-individual-time-profile.R:51:2
 2.   +-base::withCallingHandlers(...)
 3.   \-testthat::expect_snapshot_file(...)
-- Failure (test-plot-individual-time-profile.R:70:3): It respects custom plot configuration --
Snapshot of `testcase` to 'plot-individual-time-profile/custom-plot-config.svg' has changed
* Download and unzip run artifact
* Copy 'tests/testthat/_snaps/plot-individual-time-profile/custom-plot-config.new.svg' to local test directory
* Run `testthat::snapshot_review('plot-individual-time-profile/')` to review changes
Backtrace:
    x
 1. \-vdiffr::expect_doppelganger(...) at test-plot-individual-time-profile.R:70:2
 2.   +-base::withCallingHandlers(...)
 3.   \-testthat::expect_snapshot_file(...)
-- Failure (test-plot-individual-time-profile.R:89:3): It creates default plots as expected for only observed --
Snapshot of `testcase` to 'plot-individual-time-profile/default-plot-observed.svg' has changed
* Download and unzip run artifact
* Copy 'tests/testthat/_snaps/plot-individual-time-profile/default-plot-observed.new.svg' to local test directory
* Run `testthat::snapshot_review('plot-individual-time-profile/')` to review changes
Backtrace:
    x
 1. \-vdiffr::expect_doppelganger(...) at test-plot-individual-time-profile.R:89:2
 2.   +-base::withCallingHandlers(...)
 3.   \-testthat::expect_snapshot_file(...)
-- Failure (test-plot-individual-time-profile.R:109:3): It creates default plots as expected for only simulated --
Snapshot of `testcase` to 'plot-individual-time-profile/default-plot-simulated.svg' has changed
* Download and unzip run artifact
* Copy 'tests/testthat/_snaps/plot-individual-time-profile/default-plot-simulated.new.svg' to local test directory
* Run `testthat::snapshot_review('plot-individual-time-profile/')` to review changes
Backtrace:
    x
 1. \-vdiffr::expect_doppelganger(...) at test-plot-individual-time-profile.R:109:2
 2.   +-base::withCallingHandlers(...)
 3.   \-testthat::expect_snapshot_file(...)
-- Failure (test-plot-individual-time-profile.R:124:3): It works when geometric error is present --
Snapshot of `testcase` to 'plot-individual-time-profile/geometric-error.svg' has changed
* Download and unzip run artifact
* Copy 'tests/testthat/_snaps/plot-individual-time-profile/geometric-error.new.svg' to local test directory
* Run `testthat::snapshot_review('plot-individual-time-profile/')` to review changes
Backtrace:
    x
 1. \-vdiffr::expect_doppelganger(title = "geometric error", fig = plotIndividualTimeProfile(myDataCombined3)) at test-plot-individual-time-profile.R:124:2
 2.   +-base::withCallingHandlers(...)
 3.   \-testthat::expect_snapshot_file(...)
-- Error (test-plot-observed-vs-simulated.R:47:3): It creates default plots as expected --
Error in `rep(seq(1, base - 1, length.out = ticks_per_base), reps)`: invalid 'times' argument
Backtrace:
     x
  1. \-vdiffr::expect_doppelganger(title = "default plot", fig = plotObservedVsSimulated(myCombDat)) at test-plot-observed-vs-simulated.R:47:2
  2.   \-vdiffr (local) writer(fig, testcase, title)
  3.     +-vdiffr:::print_plot(plot, title)
  4.     \-vdiffr:::print_plot.ggplot(plot, title)
  5.       +-base::print(p)
  6.       \-ggplot2:::print.ggplot(p)
  7.         +-ggplot2::ggplot_gtable(data)
  8.         \-ggplot2:::ggplot_gtable.ggplot_built(data)
  9.           \-base::Map(...)
 10.             \-base::mapply(FUN = f, ..., SIMPLIFY = FALSE)
 11.               \-ggplot2 (local) `<fn>`(dots[[1L]][[9L]], dots[[2L]][[9L]])
 12.                 \-l$draw_geom(d, layout)
 13.                   \-ggplot2 (local) f(..., self = self)
 14.                     \-self$geom$draw_layer(...)
 15.                       \-ggplot2 (local) f(..., self = self)
 16.                         \-base::lapply(...)
 17.                           \-ggplot2 (local) FUN(X[[i]], ...)
 18.                             +-base::do.call(self$draw_panel, args)
 19.                             \-ggplot2 (local) `<ggprt_mt>`(...)
 20.                               \-ggplot2 (local) f(...)
 21.                                 \-ggplot2:::calc_logticks(...)
-- Failure (test-plot-observed-vs-simulated.R:59:3): It issues warning when scale is linear --
Snapshot of `testcase` to 'plot-observed-vs-simulated/linear-scale.svg' has changed
* Download and unzip run artifact
* Copy 'tests/testthat/_snaps/plot-observed-vs-simulated/linear-scale.new.svg' to local test directory
* Run `testthat::snapshot_review('plot-observed-vs-simulated/')` to review changes
Backtrace:
    x
 1. \-vdiffr::expect_doppelganger(...) at test-plot-observed-vs-simulated.R:59:2
 2.   +-base::withCallingHandlers(...)
 3.   \-testthat::expect_snapshot_file(...)
-- Error (test-plot-observed-vs-simulated.R:82:3): It respects custom plot configuration --
Error in `rep(seq(1, base - 1, length.out = ticks_per_base), reps)`: invalid 'times' argument
Backtrace:
     x
  1. \-vdiffr::expect_doppelganger(...) at test-plot-observed-vs-simulated.R:82:2
  2.   \-vdiffr (local) writer(fig, testcase, title)
  3.     +-vdiffr:::print_plot(plot, title)
  4.     \-vdiffr:::print_plot.ggplot(plot, title)
  5.       +-base::print(p)
  6.       \-ggplot2:::print.ggplot(p)
  7.         +-ggplot2::ggplot_gtable(data)
  8.         \-ggplot2:::ggplot_gtable.ggplot_built(data)
  9.           \-base::Map(...)
 10.             \-base::mapply(FUN = f, ..., SIMPLIFY = FALSE)
 11.               \-ggplot2 (local) `<fn>`(dots[[1L]][[10L]], dots[[2L]][[10L]])
 12.                 \-l$draw_geom(d, layout)
 13.                   \-ggplot2 (local) f(..., self = self)
 14.                     \-self$geom$draw_layer(...)
 15.                       \-ggplot2 (local) f(..., self = self)
 16.                         \-base::lapply(...)
 17.                           \-ggplot2 (local) FUN(X[[i]], ...)
 18.                             +-base::do.call(self$draw_panel, args)
 19.                             \-ggplot2 (local) `<ggprt_mt>`(...)
 20.                               \-ggplot2 (local) f(...)
 21.                                 \-ggplot2:::calc_logticks(...)
-- Failure (test-plot-residuals-vs-simulated.R:47:3): It creates default plots as expected --
Snapshot of `testcase` to 'plot-residuals-vs-simulated/default-plot.svg' has changed
* Download and unzip run artifact
* Copy 'tests/testthat/_snaps/plot-residuals-vs-simulated/default-plot.new.svg' to local test directory
* Run `testthat::snapshot_review('plot-residuals-vs-simulated/')` to review changes
Backtrace:
    x
 1. \-vdiffr::expect_doppelganger(title = "default plot", fig = plotResidualsVsSimulated(myCombDat)) at test-plot-residuals-vs-simulated.R:47:2
 2.   +-base::withCallingHandlers(...)
 3.   \-testthat::expect_snapshot_file(...)
-- Failure (test-plot-residuals-vs-simulated.R:80:3): It respects custom plot configuration --
Snapshot of `testcase` to 'plot-residuals-vs-simulated/customized-plot.svg' has changed
* Download and unzip run artifact
* Copy 'tests/testthat/_snaps/plot-residuals-vs-simulated/customized-plot.new.svg' to local test directory
* Run `testthat::snapshot_review('plot-residuals-vs-simulated/')` to review changes
Backtrace:
    x
 1. \-vdiffr::expect_doppelganger(...) at test-plot-residuals-vs-simulated.R:80:2
 2.   +-base::withCallingHandlers(...)
 3.   \-testthat::expect_snapshot_file(...)
-- Failure (test-plot-residuals-vs-time.R:47:3): It creates default plots as expected --
Snapshot of `testcase` to 'plot-residuals-vs-time/default-plot.svg' has changed
* Download and unzip run artifact
* Copy 'tests/testthat/_snaps/plot-residuals-vs-time/default-plot.new.svg' to local test directory
* Run `testthat::snapshot_review('plot-residuals-vs-time/')` to review changes
Backtrace:
    x
 1. \-vdiffr::expect_doppelganger(title = "default plot", fig = plotResidualsVsTime(myCombDat)) at test-plot-residuals-vs-time.R:47:2
 2.   +-base::withCallingHandlers(...)
 3.   \-testthat::expect_snapshot_file(...)
-- Failure (test-plot-residuals-vs-time.R:80:3): It respects custom plot configuration --
Snapshot of `testcase` to 'plot-residuals-vs-time/customized-plot.svg' has changed
* Download and unzip run artifact
* Copy 'tests/testthat/_snaps/plot-residuals-vs-time/customized-plot.new.svg' to local test directory
* Run `testthat::snapshot_review('plot-residuals-vs-time/')` to review changes
Backtrace:
    x
 1. \-vdiffr::expect_doppelganger(...) at test-plot-residuals-vs-time.R:80:2
 2.   +-base::withCallingHandlers(...)
 3.   \-testthat::expect_snapshot_file(...)

[ FAIL 12 | WARN 28 | SKIP 5 | PASS 995 ]
```

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
TODO:

- [x] Closes #980 
- [x] Closes #982 
- [x] Closes #1051
- [x] Closes #1052 
- [x] Closes #1056 
- [x] Closes #1058 
- [x] Closes #1059 
- [x] Closes #1060
- [x] Closes #1062
- [x] Closes #1064
- [x] Closes #1065
- [x] Closes #1066
- [x] Closes #1076
- [x] Refactor to DRY up code
- [x] Revert interpolation implemented for https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/804, since it was giving incorrect results, and there was a simpler method available that gives almost identical results
- [x] Remove all unnecessary internal utilities
- [x] Update snapshots for plot to catch up with `{tlf}` changes

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
This comes at a cost, though. 

Because we suppress legends for shape mappings (as specified [here](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/980#issuecomment-1192726622)), the legends are not that informative now. 

# Before 

image

# After

image

**Comment by PavelBal** [comment]
Hmm, this is confusing especially for the groups that do not have any simulated results. The "Stevens..." entries also show lines, though there are no data sets that contain the lines in these groups.

Instead of showing the same symbol for every legend entry, it should show the _first_ symbol used for the group.

**Comment by IndrajeetPatil** [comment]
@PavelBal Can you please provide a test example where there are:

- more than two observed datasets per group, and/or 
- more than two simulated datasets per group (does that even make sense?)

Currently, all tests have groups with only a single observed and/or simulated data per group.

**Comment by PavelBal** [comment]
Two simulated and two observed data sets per group:

```
simFilePath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
sim <- loadSimulation(simFilePath)

outputPath <- c("Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)",
                "Organism|Muscle|Intracellular|Aciclovir|Concentration")

addOutputs(outputPath, sim)
simResults <- runSimulation(sim)

obsData <- lapply(c("ObsDataAciclovir_1.pkml", "ObsDataAciclovir_3.pkml"),
                  \(x){loadDataSetFromPKML(system.file("extdata", x, package = "ospsuite"))})

names(obsData) <- lapply(obsData, \(x){x$name})


myDataCombined <- DataCombined$new()
# Add simulated results
myDataCombined$addSimulationResults(simulationResults = simResults,
                                    quantitiesOrPaths = outputPath,
                                    groups = "Aciclovir PVB")

# Add observed data set
myDataCombined$addDataSets(obsData, groups = "Aciclovir observed")

plotIndividualTimeProfile(myDataCombined)
```

image

**Comment by IndrajeetPatil** [comment]
Thanks!

**Comment by IndrajeetPatil** [comment]
Can't proceed here until https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/353 is resolved.

**Comment by PavelBal** [comment]
I see that interpolation has been removed completely? I would like to test how it behaves now, but require this feature first https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/1067

**Comment by IndrajeetPatil** [comment]
Why is #1067 needed to check that? We haven't had it thus far and have trusted the results from interpolation anyway.

Here are two examples that can be used to check if the observed and simulated data are being paired properly:

# Example-1

```r
# load the simulation
sim <- loadTestSimulation("MinimalModel")
simResults <- importResultsFromCSV(
  simulation = sim,
  filePaths = getTestDataFilePath("Stevens_2012_placebo_indiv_results.csv")
)

# import observed data (will return a list of `DataSet` objects)
dataSet <- loadDataSetsFromExcel(
  xlsFilePath = getTestDataFilePath("CompiledDataSetStevens2012.xlsx"),
  importerConfiguration = loadDataImporterConfiguration(getTestDataFilePath("ImporterConfiguration.xml"))
)

# create a new instance and add datasets
myCombDat <- DataCombined$new()
myCombDat$addDataSets(dataSet)
myCombDat$addSimulationResults(
  simResults,
  quantitiesOrPaths = c(
    "Organism|Lumen|Stomach|Metformin|Gastric retention",
    "Organism|Lumen|Stomach|Metformin|Gastric retention distal",
    "Organism|Lumen|Stomach|Metformin|Gastric retention proximal"
  )
)

myCombDat$setGroups(
  names = c(
    "Organism|Lumen|Stomach|Metformin|Gastric retention",
    "Organism|Lumen|Stomach|Metformin|Gastric retention distal",
    "Organism|Lumen|Stomach|Metformin|Gastric retention proximal",
    "Stevens_2012_placebo.Placebo_total",
    "Stevens_2012_placebo.Placebo_distal",
    "Stevens_2012_placebo.Placebo_proximal"
  ),
  groups = c("Solid total", "Solid distal", "Solid proximal", "Solid total", "Solid distal", "Solid proximal")
)

plotObservedVsSimulated(myCombDat)
```

# Example-2

```r
  simFilePath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
  sim <- loadSimulation(simFilePath)

  simResults <- runSimulation(sim)

  obsData <- lapply(
    c("ObsDataAciclovir_1.pkml", "ObsDataAciclovir_2.pkml", "ObsDataAciclovir_3.pkml"),
    function(x) loadDataSetFromPKML(system.file("extdata", x, package = "ospsuite"))
  )

  names(obsData) <- lapply(obsData, function(x) x$name)

  outputPath <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
  myDataCombined <- DataCombined$new()

  # Add simulated results
  myDataCombined$addSimulationResults(
    simulationResults = simResults,
    quantitiesOrPaths = outputPath,
    groups = "Aciclovir PVB"
  )

  # Add observed data set
  myDataCombined$addDataSets(obsData$`Vergin 1995.Iv`, groups = "Aciclovir PVB")

  plotObservedVsSimulated(myDataCombined)
```

**Comment by IndrajeetPatil** [comment]
@PavelBal Builds passing now. 

Skipping a few tests on CI that won't pass until https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/367 is resolved. But since the PR has already grown to a monstrous size, there is no reason to postpone this until all issues are resolved.

I will make a new PR once that issue is resolved.

**Review by PavelBal — APPROVED** [review]

**Pull request merged**
