### PR TITLE
move test to the correct file

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Follow up to #737

Also runs test on linux which was previously skipped

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
@msevestre Do you know where these changes are coming from? I didn't make any changes to this folder.

image

**Comment by msevestre** [comment]
You probably did not update the submodule after pulling from develop. git status would have shown normally that this was required. So you probably commited the old version of the submodule again. This needs to be reverted

**Comment by IndrajeetPatil** [comment]
> You probably did not update the submodule after pulling from develop

How am I supposed to know when I should or should not update submodules? I definitely can't keep checking commit hashes each time I pull, so I am assuming there is some trick to this.

Do you think it's worth mentioning how to update submodules here?

https://github.com/Open-Systems-Pharmacology/Suite/blob/develop/GIT_WORKFLOW.md

**Comment by msevestre** [comment]
>How am I supposed to know when I should or should not update submodules?

I am assuming that git for windows should display this. I am using Cmder and i see it right away
image

the yellow indicates some changes and the M comes from git shows that dimension is outdated

**Comment by IndrajeetPatil** [comment]
How come this was merged? I didn't revert the change to the submodule. 👀 

Thanks for the tip; I will start using `Cmder`.

**Comment by msevestre** [comment]
Oh crap..I thought you had done it. Well this needs to be reverted. Sorry

**Pull request merged**
