### PR TITLE
Add vignettes

### PR DESCRIPTION
**Pull request by PavelBal**
WIP - please feedback if the general form is OK.

### CODE REVIEW

**Comment by msevestre** [comment]
@PavelBal How can I see the output ? What's the command again?

**Comment by PavelBal** [comment]
I have the "knit"-button when such a *.md is open:

image

**Comment by PavelBal** [comment]
Or:

`rmarkdown::render(file.path(getwd(), "vignettes", "introduction-ospsuite.Rmd"))`

It generates a html in the vignettes-folder.

**Comment by msevestre** [comment]
does not work for me
image

**Comment by msevestre** [comment]
The comamnd line does nto work for me either

```
output file: introduction-ospsuite.knit.md

"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS introduction-ospsuite.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output introduction-ospsuite.html --email-obfuscation none --self-contained --standalone --section-divs --template "C:\Users\Michael\Documents\R\win-library\3.5\rmarkdown\rmd\h\default.html" --highlight-style pygments --css "C:\Users\Michael\Documents\R\win-library\3.5\rmarkdown\rmarkdown\templates\html_vignette\resources\vignette.css" --mathjax --variable "mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" 
Error: pandoc document conversion failed with error 1033
```


@pchelle How do you generate the markdown again locally? I forgot what you'd shown me a while back

Thanks

**Comment by PavelBal** [comment]
@msevestre OK, what is broken now?

**Comment by pchelle** [comment]
> 
> 
> @msevestre OK, what is broken now?

Where can I see the building fail from appveyor ?
There should be an error message there explaining why the vignette was not built.
My first guess, would be you that need to add library(ospsuite) in the vignette to load the content of the package because the vignette does not know you use the code from the package in the building of the vignette.
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(ospsuite)
```

**Comment by PavelBal** [comment]
@pchelle The library is loaded in the first chunk that actually uses the package..

**Comment by msevestre** [comment]
it's probably because I have an outdated package installed locally
I'll try again

**Comment by msevestre** [comment]
@PavelBal Can you rebase. There are merges conflicts everywhere, mostly in the automatically generated files.

**Pull request merged**
