### PR TITLE
consistently use markdown syntax in rd docs

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
I used this tool to automate this change: https://roxygen2md.r-lib.org/

We are not doing anything complicated in roxygen docs (like lists, math equations, references, etc.), so this was quite straightforward and pain-free.

**Comment by msevestre** [comment]
@IndrajeetPatil Awesome
Would you mind adding a section in the readme explaining how to use the tool (or just add a reference there for the future)

**Comment by PavelBal** [comment]
@

**Comment by msevestre** [comment]
sounds good

**Comment by IndrajeetPatil** [comment]
Wouldn't this be a better place to document this?
https://github.com/Open-Systems-Pharmacology/Suite/blob/master/CODING_STANDARDS_R.md

**Comment by msevestre** [comment]
yep agreed

**Pull request merged**
