### PR TITLE
Add default `tlf` plot theme

### LINKED ISSUE #829: Add a default `{tlf}` theme for `{ospsuite}` plots
# Task

Add a default `{tlf}` theme for `{ospsuite}` plots

# Background

_tlf_ package provides [`Theme`](https://www.open-systems-pharmacology.org/TLF-Library/reference/Theme.html) objects, which provide a single entry point to set up the _look_ of the plot by choosing:

- aesthetic mappings (what variables are mapped to `colour`, `fill`, `linetype`, etc.)
- background (watermark, legend position, grid, etc.)
- properties (colour, font, size, etc.) for the plot text (title, subtitle, legend, axes labels, etc.)

These objects are **not** involved in setting up scale transformations; that's the job of the [`Scaling` ](https://www.open-systems-pharmacology.org/TLF-Library/reference/Scaling.html)object.

As decided in our relevant meetings, we **don't** want, as much as possible, for users to be exposed to the underlying _tlf_ `R6` objects. Therefore, we will choose a theme (and thereby a _look_) in a way that satisfies most users' expectations and aesthetic preferences out of the box. 

In other words, we will try our best to include a default theme for all plotting functions that circumvents users ever having to learn how to create an instance of the `Theme` class. And, of course, those who want to change the theme will be provided with an option to provide their own home-grown `Theme` instance.

For more, see:
https://www.open-systems-pharmacology.org/TLF-Library/articles/theme-maker.html

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
I would prefer to add the theme already to the `develop` branch because it will be required in every single PR targeting implementation of a plotting function.

If we don't do this, I will need to have a copy of it in every plotting function related branch, and these copies might get out of sync with each other as the theme evolves organically based on the feedback from the team.

OTOH, if we have a copy in the `develop` branch, each PR can just modify it based on the said feedback.

To get a rough idea for the current look, have a look at [this document](https://github.com/pchelle/recreating-plots-with-tlf/blob/main/recreating-plot-with-tlf.pdf) (ignore the watermark, it's not part of the theme in this PR).

Closes #829

Co-Authored-By: Pierre Chelle <45343665+pchelle@users.noreply.github.com>

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
The CI failure is unrelated:

> Could not load type 'OSPSuite.Core.

```r
--- re-building 'create-individual.Rmd' using rmarkdown
Quitting from lines 30-49 (create-individual.Rmd) 
Error: processing vignette 'create-individual.Rmd' failed with diagnostics:
Type:    System.Reflection.ReflectionTypeLoadException
Message: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Method:  System.RuntimeType[] GetTypes(System.Reflection.RuntimeModule)
Stack trace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at OSPSuite.Utility.Container.AssemblyScanner.scanTypesInAssembly(Assembly assembly)
Type:    System.TypeLoadException
Message: Could not load type 'OSPSuite.Core.Domain.Descriptors.CriteriaOperator' from assembly 'OSPSuite.Core, Version=11.0.112.0, Culture=neutral, PublicKeyToken=null'.
Method:  
Stack trace:
Type:    System.TypeLoadException
Message: Could not load type 'OSPSuite.Core.Domain.Descriptors.CriteriaOperator' from assembly 'OSPSuite.Core, Version=11.0.112.0, Culture=neutral, PublicKeyToken=null'.
Method:  
Stack trace:
Type:    System.TypeLoadException
Message: Could not load type 'OSPSuite.Core.
--- failed re-building 'create-individual.Rmd'

```

**Comment by IndrajeetPatil** [comment]
Needless to say, this is the first draft for the default theme, and it will organically evolve with every implementation of a plotting function.

**Comment by PavelBal** [comment]
Yes, good idea.

Maybe call the file `ospsuiteTLFTheme` to make it more clear what the theme is for?

For failing build - have to update the libraries I think. esqlabsR is also failing now because of new PK-Sim.

**Review by PavelBal — APPROVED** [review]

**Comment by IndrajeetPatil** [comment]
> Maybe call the file ospsuiteTLFTheme to make it more clear what the theme is for?

Done.

**Comment by Yuri05** [comment]
Very nice!
Few thoughts/suggestions:
* It would be good to have a script, which creates example plots of each kind using the ospsuite tlf theme (e.g. a script for all the plots in https://github.com/pchelle/recreating-plots-with-tlf/blob/main/recreating-plot-with-tlf.pdf). Then any changes in the theme could be easily evaluated by users
* I don't know if it's part of the theme, but one wish from users was that as per default mean/median curves within (population) range plots are **solid** lines

**Comment by PavelBal** [comment]
@Yuri05  I created a discussion for pop specifications: https://github.com/Open-Systems-Pharmacology/OSPSuite-R/discussions/832

Definintely the color of the ranges should be more transparent, as now it is overpainting the median curves. But this will be the discussion of the default theme of this specific feature, I guess.

**Comment by IndrajeetPatil** [comment]
@Yuri05 

> e.g. a script for all the plots

The script is [here](https://github.com/pchelle/recreating-plots-with-tlf/blob/main/recreating-plot-with-tlf.Rmd). The code chunks supply the needed code to reproduce those plots, although the repo doesn't contain the datasets (@pchelle Do you still have these datasets, or should I make a PR to add them?).

I am trying to be agile here and implement one plotting function at a time per PR, which would also make it easy to change the theme incrementally and appropriately for each plot. 

> I don't know if it's part of the theme, but one wish from users was that as per default mean/median curves within (population) range plots are solid lines

Yes, this is part of the theme, and we can definitely make the necessary changes to the theme in the PR for `plotPopulationTimeProfile()`.

**Comment by msevestre** [comment]
I cannot post on github ATM
Can we have the color more pastel for shaded area? (e..g changing the
opacity or sthg).

**Comment by msevestre** [comment]
image

On this image here. Can we have the area color in more pastel tone (e..g change the transparency a bit I guess?)

**Comment by IndrajeetPatil** [comment]
@pchelle To change the transparency of ribbons, as requested by Juri and Michael, I changed the theme JSON from

```json
      "ribbons": {
        "color": "reset",
        "fill": "reset",
        "shape": "blank",
        "linetype": "blank",
        "size": 0.5,
        "alpha": "first"
      },
```

to

```json
      "ribbons": {
        "color": "reset",
        "fill": "reset",
        "shape": "blank",
        "linetype": "blank",
        "size": 0.5,
        "alpha": 0.3
      },
```

but it changes nothing. 

Is this a bug?

**Comment by IndrajeetPatil** [comment]
Same result even if I change from

```json
    "addRibbon": {
      "color": "next",
      "fill": "next",
      "shape": "blank",
      "linetype": "same",
      "size": "first",
      "alpha": "first"
    },
```

to

```json
    "addRibbon": {
      "color": "next",
      "fill": "next",
      "shape": "blank",
      "linetype": "same",
      "size": "first",
      "alpha": 0.3
    },
```

**Comment by IndrajeetPatil** [comment]
The transparency can't be changed currently due to a bug in _tlf_: https://github.com/Open-Systems-Pharmacology/TLF-Library/issues/227

I see no reason why this PR should be kept pending while that is resolved. It's blocking me from working on plotting functions.

**Comment by Yuri05** [comment]
Fine for me to merge. Is sure not the last adjustment of the theme anyway :)

**Pull request merged**
