### PR TITLE
Fixes #1190

### LINKED ISSUE #1190: Update ospsuite.core
Update to "11.1.96"

### PR DESCRIPTION
**Pull request by PavelBal**

### CODE REVIEW

**Review by Yuri05 — APPROVED** [review]

**Comment by PavelBal** [comment]
Will merge when the check is performed.

**Comment by Yuri05** [comment]
hmm
```
* checking package dependencies ... ERROR
Package required but not available: 'tlf'
See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
```
might be just a temporary glitch on AppVeyor. Will try to rebuild

**Comment by Yuri05** [comment]
@PavelBal Unfortunately I have to update OSPSuite.Core again...
https://github.com/Open-Systems-Pharmacology/InstallationValidator/pull/265#issuecomment-1403554783
So please wait with merging

**Comment by PavelBal** [comment]
> So please wait with merging

Sorry...

**Pull request merged**
