### PR TITLE
Fixes #850 Update packages for SimModel and FuncParser

### LINKED ISSUE #850: Update CentOS packages for SimModel and FuncParser
After https://github.com/Open-Systems-Pharmacology/OSPSuite.CentOS/issues/9 is done

### LINKED ISSUE #901: Update dimensions and core

### PR DESCRIPTION
**Pull request by Yuri05**
Fixes #901 Update dimensions and core

### CODE REVIEW

**Comment by msevestre** [comment]
doing it was part of the other PR. closing

**Comment by Yuri05** [comment]
>doing it was part of the other PR. closing 

all of this? also incl. the latest versions of SimModel and FuncParser (CentOS) which I created couple of hours ago? or only dimensions/Core?

**Comment by msevestre** [comment]
all of it

**Comment by Yuri05** [comment]
ok, cool.

**Pull request closed without merging**
