### PR TITLE
fixes tests for R3?

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Related to-
#762
#906

For reasons mentioned in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/762#issuecomment-1105076491

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
@msevestre, @Yuri05 How should we do this?

We've two options:
- Merge this to `develop` and then trigger a new build on AppVeyor-3.6
- Yuri runs tests locally with this branch and checks if the tests pass on R 3.6, and then merge to `develop`

**Comment by msevestre** [comment]
Once the changes are ok on appveyor on develop, I'll merge. 
What is the implication of your fix. Is this going to change how the returned DF is behaving. This is effectively a break in the shape of the df correct?

**Comment by IndrajeetPatil** [comment]
This doesn't change _anything_. 

The tests failed due to different **default** behaviour of `data.frame()` function for R versions `>= 4.0` and `< 4.0` due to the following [change](https://cran.r-project.org/bin/windows/base/old/4.0.0/NEWS.R-4.0.0.html) introduced in `R 4.0`:

> R now uses a stringsAsFactors = FALSE default, and hence by default no longer converts strings to factors in calls to data.frame() and read.table().

So the tests failed on `R < 4.0`, but not on `R > 4.0`. 
Explicitly setting `stringsAsFactors = FALSE` makes the default behavior consistent across these two R versions.

**Comment by IndrajeetPatil** [comment]
`stringsAsFactors` parameter default value was notorious before it was changed in R4 and had been a source of long-standing headache for all R users (and, as we are experiencing, continue to be). 

This is a good read that explains what the fuss is all about:
https://simplystatistics.org/posts/2015-07-24-stringsasfactors-an-unauthorized-biography/

**Pull request merged**
